name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: CI
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run CI
        run: xcodebuild clean test -workspace Fractal.xcworkspace -scheme DesignSystem -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'
      
